### ISSUE TITLE
Requires .NET 2

### ISSUE THREAD

**Issue by jspraul** [tyranid/DotNetToJScript#1]
Not sure if you just didn't get into detail onto why .NET 2 is required, or are still looking into options. Here is some info on how to setup a registration-free .NET 4 COM component with a manifest file.

http://stackoverflow.com/questions/2382927/can-i-use-a-net-4-0-library-in-a-net-2-0-application

http://blogs.microsoft.co.il/arik/2011/05/30/how-to-use-a-net-4-based-dll-from-net-2-based-application/

**Comment by tyranid** [comment]
Thanks for the comment. The reason is down to the COM objects the resulting JScript file uses are only registered to use .NET v2 and sadly mscoree doesn't try and use the v4 versions of the classes (even though that'd work). You could almost certainly get around it by playing games with adding registry keys or manifests but that is more than I felt was necessary, this is really more of a PoC than anything I would expect anyone to use in the real world. 

Of course the reason the tool itself bails if you compile with v4 is just down to ensuring the serialized data is for the correct version.

**Comment by qgrosperrin** [comment]
I have .NET 2/3/3.5/4/4.5 installed on my system, but when using `csc` it specifically mentions .NET 4.5. The resulting file works properly.

```
>csc example.cs
Microsoft (R) Visual C# Compiler version 4.6.1087.0
for Microsoft (R) .NET Framework 4.5
Copyright (C) Microsoft Corporation. All rights reserved.
```

Does this mean the assembly was targeted for 4.5 but it still works ?

**Comment by tyranid** [comment]
The executable still needs v2 installed but the resulting script can now run on v2 or v4 (using the -ver auto command) so closing this.
